# Generated by Django 5.2.7 on 2025-10-28 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=200)),
                ("partido_politico", models.CharField(max_length=100)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="candidatos/"),
                ),
                ("propuesta", models.TextField()),
                ("numero", models.IntegerField(unique=True)),
                ("votos", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Candidatos",
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="Ciudadano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cedula", models.CharField(max_length=20, unique=True)),
                ("nombre_completo", models.CharField(max_length=200)),
                ("fecha_nacimiento", models.DateField()),
                ("direccion", models.TextField()),
                ("ha_votado", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ciudadanos",
            },
        ),
        migrations.CreateModel(
            name="Voto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="votacion.candidato",
                    ),
                ),
                (
                    "ciudadano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="votacion.ciudadano",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Votos",
                "unique_together": {("ciudadano",)},
            },
        ),
    ]
